name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa todo dia à meia-noite UTC
  workflow_dispatch: # Permite acionamento manual

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão de escrita para o repositório, essencial para commitar

    steps:
      # Passo 1: Faz o checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      # DEBUG: Verifica o conteúdo antes de gerar a cobrinha (opcional, pode remover depois)
      - name: Debug - Before snake generation
        run: |
          echo "Conteúdo do diretório de trabalho antes da geração da cobrinha:"
          ls -la

      # Passo 2: Gera a animação da cobrinha
      - name: Generate snake SVG
        uses: Platane/snk@v3
        id: snake-generator # ID para referenciar este passo
        with:
          github_user_name: guimattee # Seu username GitHub
          outputs: dist/snake.svg, dist/snake-dark.svg # Onde a cobrinha será gerada

      # DEBUG: Verifica o conteúdo da pasta dist APÓS a geração da cobrinha (opcional, pode remover depois)
      - name: Debug - After snake generation
        run: |
          echo "Conteúdo da pasta 'dist/' após a geração da cobrinha:"
          ls -la dist/ || echo "Pasta 'dist/' não encontrada!"
        if: success()

      # Passo 3: Commita os arquivos gerados de volta para o repositório
      # Usamos a action 'git-auto-commit-action' para isso, que é mais robusta.
      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v5 # <-- NOVA ACTION AQUI
        with:
          commit_message: "Generated snake animation [skip ci]" # Mensagem do commit
          branch: main # Garante que o commit vá para a branch principal
          # Este parâmetro garante que a ação funcione mesmo se não houver mudanças, evitando falhas
          create_branch: false
          # O caminho para os arquivos que devem ser commitados.
          # O diretório de trabalho padrão é o root do repo, então 'dist/' já funciona.
          file_pattern: 'dist/snake.svg dist/snake-dark.svg'
        # Condição para rodar este passo APENAS se a geração da cobrinha foi bem-sucedida
        if: success() && steps.snake-generator.outputs.outputs != ''
